services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
      DB_NAME: postgres
      DB_HOST: postgres_dev
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis_dev
      REDIS_PORT: 6379
      REDIS_PW: redispw
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SCRET_KEY: ${JWT_SECRET_KEY}
      REFRESH_SECRET_KEY: ${REFRESH_SECRET_KEY}

      # - PYTHONPATH=/app
      # - DB_NAME=postgres
      # - DB_HOST=postgres_dev
      # - DB_PORT=5432
      # - DB_USER=postgres
      # - DB_PASSWORD=postgres
      # - REDIS_HOST=redis_dev
      # - REDIS_PORT=6379
      # - REDIS_PW=redispw
      # - OPENAI_API_KEY=${OPENAI_API_KEY}
      # - JWT_SCRET_KEY=${JWT_SECRET_KEY}
      # - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
  postgres:
    image: postgres
    container_name: postgres_dev
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./dev_resources/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis
    container_name: redis_dev
    ports:
      - 6379:6379
    command: /bin/sh -c "redis-server --requirepass redispw"
