services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - PYTHONPATH=/app
  postgres:
    image: postgres
    container_name: postgres_dev
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./dev_resources/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis
    container_name: redis_dev
    ports:
      - 6379:6379
    command: /bin/sh -c "redis-server --requirepass redispw"
