services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
      DB_NAME: master
      DB_HOST: postgres_dev
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis_dev
      REDIS_PORT: 6379
      REDIS_PW: redispw
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      JWT_SCRET_KEY: ${JWT_SECRET_KEY}
      REFRESH_SECRET_KEY: ${REFRESH_SECRET_KEY}
      TEST_ENV: ${TEST_ENV}
      GROQ_API_KEY: ${GROQ_API_KEY}
      AWS_BEDROCK_ACCESS_KEY: ${AWS_BEDROCK_ACCESS_KEY}
      AWS_BEDROCK_SECRET_KEY: ${AWS_BEDROCK_SECRET_KEY}
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres_dev
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./dev_resources/init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis
    container_name: redis_dev
    ports:
      - 6379:6379
    command: /bin/sh -c "redis-server --requirepass redispw"
