version: '3'

tasks:
  up:
    cmds:
      - docker compose up
  build:
    cmds:
      - docker compose up --build
  down:
    cmds:
      - docker compose down
  exec:
    cmds:
      - aws ecs execute-command --cluster interview-ai-server --task {{.TASK_ARN}} --container interview-ai-server --interactive --command "/bin/bash"
    vars:
      TASK_ARN:
        sh: aws ecs list-tasks --cluster interview-ai-server | jq -r '.taskArns[0]'
  run:
    cmds:
      - uvicorn app.main:app --host 0.0.0.0 --port 8000
  migrate-prod:
    cmds:
      - flyway migrate -environment=prod
  migrate-dev:
    cmds:
      - flyway migrate -environemnt=dev
  connect-dev-db:
    cmds:
      - psql -h localhost -p 5432 -U postgres -d postgres
  redis-cli-dev:
    cmds:
      - docker exec -it {{.CONTAINER_ID}} redis-cli
    vars:
      CONTAINER_ID:
        sh: docker ps -qf "name=redis_dev"