version: '3'

tasks:
  up:
    cmds:
      - docker compose up --build
  down:
    cmds:
      - docker compose down
  exec:
    cmds:
      - aws ecs execute-command --cluster interview-ai-server --task {{.TASK_ARN}} --container interview-ai-server --interactive --command "/bin/bash"
    vars:
      TASK_ARN:
        sh: aws ecs list-tasks --cluster interview-ai-server | jq -r '.taskArns[0]'
  test:
    cmds:
      - python tests/test_ws.py
  run:
    cmds:
      - uvicorn app.main:app --host 0.0.0.0 --port 8000
  migrate-prod:
    cmds:
      - flyway migrate -environment=prod
  migrate-dev:
    cmds:
      - flyway migrate -environemnt=dev
  connect-db:
    cmds:
      - psql -h db.zwlrkwwxehylioimgswa.supabase.co -p 5432 -d postgres -U postgres